name: ubuntu-rvm

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 'ruby-head' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@master
    - name: Set up RVM
      run: |
        curl -sSL https://get.rvm.io | bash
    - name: Set up Ruby
      run: |
        source $HOME/.rvm/scripts/rvm
        if [[ "${{ matrix.ruby }}" == "ruby-head" ]]; then
          rvm install 2.7.0 --binary # some ruby is required for no --binary
          rvm install ${{ matrix.ruby }}
        else
          rvm install ${{ matrix.ruby }} --binary
        fi
        rvm --default use ${{ matrix.ruby }}
    - name: Set up Bundler
      run: |
        source $HOME/.rvm/scripts/rvm
        gem install bundler --no-document
    - name: Install dependencies
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle install
    - name: Run test
      run: |
        source $HOME/.rvm/scripts/rvm
        rake
